# Katas 10

## Dataset

Continuer l'exploration du dataset kickstarter

Calculer le montant moyen par donnateur et cr√©er une nouvelle colonne 'average_pledge' dans le dataframe

In [49]:
import pandas as pd
df = pd.read_csv('ks-projects-201801.csv',sep=',',error_bad_lines=False,encoding ='latin1', header=0, index_col=0)
df.columns

Index(['name', 'category', 'main_category', 'currency', 'deadline', 'goal',
       'launched', 'pledged', 'state', 'backers', 'country', 'usd pledged',
       'usd_pledged_real', 'usd_goal_real'],
      dtype='object')

In [33]:
df

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
ID,,,,,,,,,,,,,,,,
1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09 11:36:00,1000,2015-08-11 12:12:28,0,failed,0,GB,0,NaN,NaN,NaN,NaN
1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26 00:20:50,45000,2013-01-12 00:20:50,220,failed,3,US,220,NaN,NaN,NaN,NaN
1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16 04:24:11,5000,2012-03-17 03:24:11,1,failed,1,US,1,NaN,NaN,NaN,NaN
1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29 01:00:00,19500,2015-07-04 08:35:03,1283,canceled,14,US,1283,NaN,NaN,NaN,NaN
1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01 13:38:27,50000,2016-02-26 13:38:27,52375,successful,224,US,52375,NaN,NaN,NaN,NaN
1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21 18:30:44,1000,2014-12-01 18:30:44,1205,successful,16,US,1205,NaN,NaN,NaN,NaN
1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17 19:05:12,25000,2016-02-01 20:05:12,453,failed,40,US,453,NaN,NaN,NaN,NaN
1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29 18:14:43,125000,2014-04-24 18:14:43,8233,canceled,58,US,8233,NaN,NaN,NaN,NaN
100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10 21:55:48,65000,2014-07-11 21:55:48,6240.57,canceled,43,US,6240.57,NaN,NaN,NaN,NaN
100004721,Of Jesus and Madmen,Nonfiction,Publishing,CAD,2013-10-09 18:19:37,2500,2013-09-09 18:19:37,0,failed,0,CA,0,NaN,NaN,NaN,NaN
100005484,Lisa Lim New CD!,Indie Rock,Music,USD,2013-04-08 06:42:58,12500,2013-03-09 06:42:58,12700,successful,100,US,12700,NaN,NaN,NaN,NaN
1000055792,The Cottage Market,Crafts,Crafts,USD,2014-10-02 17:11:50,5000,2014-09-02 17:11:50,0,failed,0,US,0,NaN,NaN,NaN,NaN
1000056157,G-Spot Place for Gamers to connect with eachot...,Games,Games,USD,2016-03-25 22:01:12,200000,2016-02-09 23:01:12,0,failed,0,US,0,NaN,NaN,NaN,NaN
1000064368,Survival Rings,Design,Design,USD,2015-02-28 02:10:53,2500,2015-01-29 02:10:53,664,failed,11,US,664,NaN,NaN,NaN,NaN
1000064918,The Beard,Comic Books,Comics,USD,2014-11-08 22:27:52,1500,2014-10-09 22:27:52,395,failed,16,US,395,NaN,NaN,NaN,NaN
1000068480,Notes From London: Above & Below,Art Books,Publishing,USD,2015-05-10 21:20:54,3000,2015-04-10 21:20:54,789,failed,20,US,789,NaN,NaN,NaN,NaN
1000070642,Mike Corey's Darkness & Light Album,Music,Music,USD,2012-08-17 14:11:32,250,2012-08-02 14:11:32,250,successful,7,US,250,NaN,NaN,NaN,NaN
1000071625,Boco Tea,Food,Food,USD,2012-06-02 17:24:32,5000,2012-05-03 17:24:32,1781,failed,40,US,1781,NaN,NaN,NaN,NaN
1000072011,CMUK. Shoes: Take on Life Feet First.,Fashion,Fashion,USD,2013-12-30 07:06:11,20000,2013-11-25 07:06:11,34268,successful,624,US,34268,NaN,NaN,NaN,NaN
1000082254,Alice in Wonderland in G Minor,Theater,Theater,USD,2014-06-15 10:09:03,3500,2014-05-16 10:10:38,650,failed,12,US,650,NaN,NaN,NaN,NaN
1000087442,Mountain brew: A quest for alcohol sustainability,Drinks,Food,NOK,2015-02-25 19:17:33,500,2015-01-26 19:17:33,48,failed,3,NO,6.18000816,NaN,NaN,NaN,NaN
1000091520,The Book Zoo - A Mini-Comic,Comics,Comics,USD,2014-11-12 17:15:50,175,2014-10-23 17:15:50,701.66,successful,66,US,701.66,NaN,NaN,NaN,NaN
1000102741,Matt Cavenaugh & Jenny Powers make their 1st a...,Music,Music,USD,2011-01-06 23:16:50,10000,2010-12-07 23:16:50,15827,successful,147,US,15827,NaN,NaN,NaN,NaN
1000103948,Superhero Teddy Bear,DIY,Crafts,GBP,2016-01-05 20:09:06,12000,2015-12-06 20:09:06,0,failed,0,GB,0,NaN,NaN,NaN,NaN
1000104688,Permaculture Skills,Webseries,Film & Video,CAD,2014-12-14 18:02:00,17757,2014-11-14 18:02:00,48905,successful,571,CA,43203.2511447,NaN,NaN,NaN,NaN
1000104953,Rebel Army Origins: The Heroic Story Of Major ...,Comics,Comics,GBP,2016-01-28 16:59:29,100,2015-12-29 16:59:29,112.38,successful,27,GB,167.7003057894,NaN,NaN,NaN,NaN
1000115172,Daily Brew Coffee,Food Trucks,Food,GBP,2015-03-31 18:06:32,3500,2015-03-01 18:06:32,21,failed,1,GB,32.41526106,NaN,NaN,NaN,NaN
1000117861,Ledr workbook: one tough journal!,Product Design,Design,USD,2016-10-08 02:00:00,1000,2016-09-07 13:14:26,47266,successful,549,US,11253,NaN,NaN,NaN,NaN
1000120151,Feather Cast Furled Fly Fishing Leaders,Product Design,Design,AUD,2015-08-22 03:09:43,2000,2015-07-23 03:09:43,2000,successful,18,AU,1473.6189,NaN,NaN,NaN,NaN
1000120287,BB130A,Public Art,Art,USD,2013-03-24 00:07:28,25000,2013-02-12 01:07:28,1395,failed,30,US,1395,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999810803,The Finger (Canceled),Documentary,Film & Video,USD,2010-12-31 21:41:15,28559,2010-12-01 21:41:15,50,canceled,1,US,50,NaN,NaN,NaN,NaN
999811847,"""100 PHOTOGRAPHS FOR OUR LIBERTIES""",Fine Art,Photography,EUR,2015-12-10 22:06:44,5000,2015-11-25 22:06:44,1574,failed,37,FR,1673.7131361,NaN,NaN,NaN,NaN
999814955,Collinwood Needs Coffee!!!,Restaurants,Food,USD,2014-07-28 13:28:12,12000,2014-06-28 13:28:12,2090,failed,42,US,2090,NaN,NaN,NaN,NaN
999829547,PookieCat rune cards - funny oracle cards for ...,Illustration,Art,EUR,2016-06-07 09:33:08,1500,2016-05-08 09:33:08,1699,successful,39,NL,1937.69716526,NaN,NaN,NaN,NaN
999832803,MONSTROCARDS- A Creative Drawing Game of Horri...,Playing Cards,Games,USD,2014-10-03 19:53:50,10000,2014-09-03 19:53:50,13861.5,successful,413,US,13861.5,NaN,NaN,NaN,NaN
99984851,"""Loreto""",Comedy,Film & Video,USD,2014-06-05 06:00:00,12000,2014-05-06 23:50:34,0,failed,0,US,0,NaN,NaN,NaN,NaN
999865831,STATE OF G - Men's Blazer Jacket & Women's Car...,Apparel,Fashion,USD,2014-12-13 04:00:00,25000,2014-11-13 17:16:17,11643,failed,97,US,11643,NaN,NaN,NaN,NaN
999867839,Transcaucasia,Photography,Photography,USD,2011-01-08 02:43:59,4000,2010-11-08 02:43:59,3531,failed,37,US,3531,NaN,NaN,NaN,NaN
99987261,"You're Not Cis, You Just Think You Are: My Enb...",Nonfiction,Publishing,USD,2015-09-24 22:37:14,800,2015-08-25 22:37:14,70,failed,5,US,70,NaN,NaN,NaN,NaN
999877902,Little Saturday's Debut Album,Country & Folk,Music,CAD,2014-12-17 17:50:12,5000,2014-11-17 17:50:12,5435,successful,78,CA,4814.8774787,NaN,NaN,NaN,NaN
999880710,Terminal Uniqueness,Nonfiction,Publishing,USD,2014-08-15 02:10:39,5000,2014-07-15 02:10:39,18,failed,5,US,18,NaN,NaN,NaN,NaN
999884445,Superette Tea - Boldly Caffeinated Loose Leaf Tea,Drinks,Food,USD,2015-12-03 13:04:14,5000,2015-11-03 13:04:14,5579,successful,103,US,5579,NaN,NaN,NaN,NaN
999893629,Ciridian Helix (Canceled),Fiction,Publishing,USD,2014-09-11 21:33:00,1000,2014-08-08 21:49:31,100,canceled,2,US,100,NaN,NaN,NaN,NaN
99991751,Here is the oasis for the youngest in the world.,Product Design,Design,CHF,2015-09-04 18:00:47,80000,2015-07-06 18:00:47,0,failed,0,CH,0,NaN,NaN,NaN,NaN
999931480,Google Glass Shield (Canceled),3D Printing,Technology,USD,2014-05-26 20:22:45,6500,2014-05-05 20:22:45,0,canceled,0,US,0,NaN,NaN,NaN,NaN
999934908,The Manual Bar Blade,Product Design,Design,USD,2015-12-15 06:59:00,3500,2015-11-23 07:33:14,6169,successful,120,US,6169,NaN,NaN,NaN,NaN
999941823,The Chronicles of Erinoth - A Graphic Novel,Comics,Comics,GBP,2013-10-10 22:45:26,16000,2013-09-10 22:45:26,2738,failed,38,GB,4281.1485734,NaN,NaN,NaN,NaN
999943841,The Dog Coffee Book,Children's Books,Publishing,USD,2013-11-30 19:03:00,950,2013-10-18 21:35:04,1732.02,successful,31,US,1732.02,NaN,NaN,NaN,NaN
999950812,The Cease is Increase,Nonfiction,Publishing,USD,2012-09-14 17:11:00,4999,2012-08-15 17:11:00,980,failed,16,US,980,NaN,NaN,NaN,NaN
999955533,Cards and Chit Network Season 2! (Canceled),Tabletop Games,Games,USD,2016-02-23 16:03:27,500,2016-01-24 16:03:27,121,canceled,5,US,121,NaN,NaN,NaN,NaN
99996661,Date Seat - Boston iOS App,Apps,Technology,USD,2016-09-05 05:59:00,6000,2016-07-29 15:36:29,0,failed,0,US,0,NaN,NaN,NaN,NaN
999969812,AT THE BEACH,Classical Music,Music,CAD,2014-03-22 00:00:16,5000,2014-02-20 01:00:16,5501,successful,78,CA,5019.92088197,NaN,NaN,NaN,NaN
999971898,Beach Wrestling Documentary,Documentary,Film & Video,NOK,2015-04-28 21:30:33,20000,2015-03-29 21:30:33,21500,successful,36,NO,2698.974335,NaN,NaN,NaN,NaN
999972264,Islanda,Documentary,Film & Video,USD,2012-03-16 03:31:10,1700,2012-02-15 04:31:10,25,failed,1,US,25,NaN,NaN,NaN,NaN
999976312,Angela's Poetry (Canceled),Poetry,Publishing,CAD,2014-09-20 03:46:07,5500,2014-08-06 03:46:07,0,canceled,0,CA,0,NaN,NaN,NaN,NaN
999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17 02:35:30,50000,2014-09-17 02:35:30,25,canceled,1,US,25,NaN,NaN,NaN,NaN
999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19 03:35:14,1500,2011-06-22 03:35:14,155,failed,5,US,155,NaN,NaN,NaN,NaN
999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16 05:59:00,15000,2010-07-01 19:40:30,20,failed,1,US,20,NaN,NaN,NaN,NaN
999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13 02:00:00,15000,2016-01-13 18:13:53,200,failed,6,US,200,NaN,NaN,NaN,NaN
999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16 09:07:47,2000,2011-07-19 09:07:47,524,failed,17,US,524,NaN,NaN,NaN,NaN

In [53]:
#df.info(verbose=True)
df['average_pledge'] = df['usd_goal_real']  / (df['backers'])
df.head()

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,average_pledge
ID,,,,,,,,,,,,,,,
1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,inf
1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,2.000000e+03
1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,1.500000e+04
1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,5.000000e+03
1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,1.392857e+03

In [22]:
#df['usd pledged '].unique
df.groupby(['backers ', 'usd pledged ']).mean()

                         Unnamed: 16
backers    usd pledged
0          0                     NaN
           0.75240299            NaN
           1                     NaN
           10                    NaN
           100                   NaN
           109                   NaN
           12.19647407           NaN
           131                   NaN
           14.4547314            NaN
           145                   NaN
           15                    NaN
           168.435237            NaN
           2.57295948            NaN
           2.9035038             NaN
           20                    NaN
           200                   NaN
           218                   NaN
           24                    NaN
           25                    NaN
           28                    NaN
           3                     NaN
           30                    NaN
           40                    NaN
           42.18276645           NaN
           47                    NaN
           5                     NaN
           5.52547245            NaN
           50                    NaN
           50.894226             NaN
           52                    NaN
...                              ...
999        97917.14              NaN
9991       1710713.62            NaN
canceled   AU                    NaN
           CA                    NaN
           GB                    NaN
           IT                    NaN
           NL                    NaN
           US                    NaN
failed     AU                    NaN
           CA                    NaN
           DE                    NaN
           FR                    NaN
           GB                    NaN
           IE                    NaN
           NL                    NaN
           NZ                    NaN
           SE                    NaN
           SG                    NaN
           US                    NaN
live       GB                    NaN
           SE                    NaN
           US                    NaN
successful AU                    NaN
           CA                    NaN
           ES                    NaN
           FR                    NaN
           GB                    NaN
           NL                    NaN
           US                    NaN
undefined  N,"0                  NaN

[174722 rows x 1 columns]

Afficher l'√©cart moyen entre le montant r√©colt√© et le montant demand√© pour les projets n'ayant par r√©ussi

In [39]:
#projet n'ayant pas reussi 
s = df.groupby(['state ', 'goal ']).std().reset_index()
s.loc[s['state '] == "failed"]

      state       goal   Unnamed: 16
2351  failed       0.15          NaN
2352  failed        0.5          NaN
2353  failed          1          NaN
2354  failed       1.85          NaN
2355  failed         10          NaN
2356  failed        100          NaN
2357  failed       1000          NaN
2358  failed      10000          NaN
2359  failed     100000          NaN
2360  failed    1000000          NaN
2361  failed   10000000          NaN
2362  failed  100000000          NaN
2363  failed     100001          NaN
2364  failed      10001          NaN
2365  failed      10007          NaN
2366  failed       1001          NaN
2367  failed      10010          NaN
2368  failed      10016          NaN
2369  failed       1002          NaN
2370  failed      10020          NaN
2371  failed      10025          NaN
2372  failed      10030          NaN
2373  failed   10035.35          NaN
2374  failed     100385          NaN
2375  failed       1004          NaN
2376  failed      10047          NaN
2377  failed      10056          NaN
2378  failed      10057          NaN
2379  failed      10060          NaN
2380  failed      10065          NaN
...      ...        ...          ...
7514  failed       9950          NaN
7515  failed      99500          NaN
7516  failed     995000          NaN
7517  failed       9952          NaN
7518  failed       9957          NaN
7519  failed        996          NaN
7520  failed        997          NaN
7521  failed       9972          NaN
7522  failed       9974          NaN
7523  failed       9975          NaN
7524  failed        998          NaN
7525  failed       9980          NaN
7526  failed     998000          NaN
7527  failed       9987          NaN
7528  failed        999          NaN
7529  failed     999.99          NaN
7530  failed       9990          NaN
7531  failed      99900          NaN
7532  failed     999000          NaN
7533  failed       9991          NaN
7534  failed       9993          NaN
7535  failed       9995          NaN
7536  failed       9997          NaN
7537  failed    9997.95          NaN
7538  failed       9999          NaN
7539  failed    9999.99          NaN
7540  failed      99990          NaN
7541  failed      99991          NaN
7542  failed      99999          NaN
7543  failed   99999.99          NaN

[5193 rows x 3 columns]

Calculer le montant median par categorie

In [44]:
 df.groupby(['goal ', 'category ']).median().reset_index()

                goal                            category   Unnamed: 16
0                0.01                      Conceptual Art          NaN
1                0.01                             Fiction          NaN
2                0.15                              Shorts          NaN
3                 0.5                         Documentary          NaN
4                   1                            Academic          NaN
5                   1                         Accessories          NaN
6                   1                           Animation          NaN
7                   1                         Anthologies          NaN
8                   1                             Apparel          NaN
9                   1                                Apps          NaN
10                  1                                 Art          NaN
11                  1                           Art Books          NaN
12                  1                    Children's Books          NaN
13                  1                     Classical Music          NaN
14                  1                              Comedy          NaN
15                  1                         Comic Books          NaN
16                  1                              Comics          NaN
17                  1                      Conceptual Art          NaN
18                  1                      Country & Folk          NaN
19                  1                              Crafts          NaN
20                  1                                 DIY          NaN
21                  1                     DIY Electronics          NaN
22                  1                              Design          NaN
23                  1                         Digital Art          NaN
24                  1                         Documentary          NaN
25                  1                               Drama          NaN
26                  1                              Drinks          NaN
27                  1                    Electronic Music          NaN
28                  1                        Experimental          NaN
29                  1                               Faith          NaN
...               ...                                 ...          ...
37178           99990                        Film & Video          NaN
37179           99991                          Technology          NaN
37180           99998                      Product Design          NaN
37181           99999                         Accessories          NaN
37182           99999                           Animation          NaN
37183           99999                              Comics          NaN
37184           99999                               Drama          NaN
37185           99999                            Hardware          NaN
37186           99999                             Hip-Hop          NaN
37187           99999                      Product Design          NaN
37188           99999                          Publishing          NaN
37189           99999                            Software          NaN
37190           99999                          Technology          NaN
37191           99999                          Television          NaN
37192           99999                           Thrillers          NaN
37193        99999.99                          Nonfiction          NaN
37194          999999                              Design          NaN
37195          999999                  Interactive Design          NaN
37196         Fashion                        dress shirts          NaN
37197    Film & Video                        Buenos Aires          NaN
37198             GBP                         Create Jobs          NaN
37199  Graphic Novels                             Angels          25.0
37200      Publishing                               Enjoy          NaN
37201             USD                     BEGGARS BANQUET          NaN
37202             USD                              Gentle          NaN
37203             USD   ME (V.isual I.nteractive A.rchive          NaN
37204             USD                       Path of Light          NaN
37205             USD        USA-made products Series One          NaN
37206             USD                         Wear Wisdom          NaN
37207             USD                        personalized          NaN

[37208 rows x 3 columns]

One hot encoder la colonne status

In [ ]:
#encoder la colonne

## Mod√®le

Cr√©er un r√©seau feedforward √† 3 couches avec keras

Coder la fonction `convolution(np_image, patch)` faisant la convolution d'une image par un neurone convolutif

## Math

Donner la formule de la fonction de co√ªt de la r√©gression logistique

In [ ]:
log(1)=0
def

Calculer √† la main le gradient de $f(x_1, x_2, x_3) =  ln(x_1^{x_2}) + exp(\theta) * cos(x_3^2)$